### ISSUE TITLE
undefined png

### ISSUE THREAD

**Issue by koppi** [johannesboyne/node-dxf-to-png#3]
Running
```bash
$ node-dxf-to-png -i halterung-68x30.dxf  -w 400 -m true -o 1.png
```
doesn't give me a png, the contents of 1.png is:
```bash
$ cat 1.png
undefined
```
[halterung-68x30.dxf](https://gist.github.com/koppi/f23e9117738a7b9fb0ca)

Can you help?

**Comment by johannesboyne** [comment]
Hi koppi,
Thanks for filing this issue, I'll try to find some space for looking into this issue.

**Comment by johannesboyne** [comment]
Hello @koppi I've found the problem.
`node-dxf-to-png` uses my library `node-dxf` this is used to parse `AcDbPolylines` and in your sample file `halterung-68x30.dxf` no instances of `AcDbPolylines`.
Is the `halterung-68x30.dxf` DXF 2000 encoded and are polylines used?

Cheers,
Johannes

**Comment by koppi** [comment]
The file in question contains only LINE and ARC elements.

**Comment by johannesboyne** [comment]
Mhm... I've created a new Issue for `node-dxf` see https://github.com/johannesboyne/node-dxf/issues/3 because it relates to this package and I'll close this issue instead. If you like you are very welcome to create a PR to support LINES and ARC Elements ;-) otherwise I'll put it on my Todo-List.
